### ISSUE TITLE
Body padding on small screens

### ISSUE THREAD

**Issue by Crisfole** [apsislabs/apsisio#33]
We need padding for the body on small screens.

_Maybe_:

```css
#content {
  margin: 0 1em;
}
```
